#!/bin/bash
# 🚀 INICIO RÁPIDO - Despliegue en 20 Minutos

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   SISTEMA DE ENCUESTAS - DESPLIEGUE A PRODUCCIÓN          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📊 Estado: ✅ 100% LISTO PARA DESPLIEGUE"
echo ""
echo "⚡ PASOS RÁPIDOS:"
echo ""
echo "PASO 1: GITHUB (5 min)"
echo "  1. Crear repo en https://github.com/new"
echo "  2. git add ."
echo "  3. git commit -m 'Desplegar'"
echo "  4. git push"
echo ""
echo "PASO 2: RENDER (5 min)"
echo "  1. Ir a https://render.com"
echo "  2. Conectar GitHub"
echo "  3. Crear Web Service"
echo "  4. Añadir MONGODB_URI"
echo "  5. Click Deploy"
echo ""
echo "PASO 3: VERIFICAR (5 min)"
echo "  1. Esperar despliegue"
echo "  2. Probar en navegador"
echo "  3. ✅ Online!"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📚 DOCUMENTACIÓN IMPORTANTE:"
echo ""
echo "   1. TODO_LISTO.md           ← Resumen completo"
echo "   2. RESUMEN_EJECUTIVO.md    ← Motivación"
echo "   3. DESPLIEGUE_RAPIDO.md    ← Pasos detallados"
echo "   4. CHECKLIST_DESPLIEGUE.md ← Verificación"
echo "   5. INDICE.md               ← Todos los docs"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "✅ PRE-REQUISITOS:"
echo ""
npm --version && echo "   ✅ npm instalado" || echo "   ❌ npm NO instalado"
node --version && echo "   ✅ Node.js instalado" || echo "   ❌ Node.js NO instalado"
git --version 2>&1 | head -1 && echo "   ✅ Git instalado" || echo "   ❌ Git NO instalado"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "🧪 TESTS:"
npm test 2>&1 | tail -3
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "🎯 PRÓXIMO PASO:"
echo ""
echo "   Abre: DESPLIEGUE_RAPIDO.md"
echo "   Sigue los pasos"
echo "   ¡Tu app estará online en 20 minutos!"
echo ""
echo "═══════════════════════════════════════════════════════════"
